server:
  port: 3344

spring:
  application:
    name: cloud-config-center # 注册进Eureka服务器的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xshwhy/springcloud-config.git  # github上面的git仓库名字
          ### 搜索目录
          search-paths:
            - springcloud-config
      ### 读取分支
      label: master
  #rabbit相关配置 15672是web管理界面的端口，5672是MQ访问的端口 116.62.148.11
  rabbitmq:
    host: 120.26.142.247
    port: 5672
    username: guest
    password: guest

  # 服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/ #单机模式

# rabbitmq相关配置  暴露bus刷新配置的端点
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'
