server:
  port: 8802

spring:
  application:
    name: cloud-stream-consumer
  cloud:
    stream:
      binders:  # 设置需要绑定的rabbitmq的服务信息
        defaultRabbit: # 表示定义的名称，binding整合
          type: rabbit  # 消息组件类型是RabbitMQ
          environment:  # 设置RabbitMQ的环境变量
            spring:
              rabbitmq:
                host: 120.26.142.247
                port: 5672
                username: guest
                password: guest
                virtual_host: /
      bindings:  #服务的整合处理
        input:  #这个名字是一个通道的名称
          destination: output  #表示要使用的Exchange名称
          #content-type: application/json  #设置消息类型，本次为json，文本则设置“text/plain"
          binder: defaultRabbit #设置要绑定的消息服务的具体设置
          group: xsh
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    lease-renewal-interval-in-seconds: 2 # 设置心跳的间隔时间，默认30
    lease-expiration-duration-in-seconds: 5 # 超过5秒间隔，默认90
    instance-id: receive-8802.com #主机名
    prefer-ip-address: true # 显示ip

management:
  health:
    rabbit:
      enabled: false