server:
  port: 81

eureka:
  client:
    #  表示是否将自己注册EurekaServer默认是true
    register-with-eureka: false
    service-url:
      # 设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://localhost:7001/eureka/ #单机模式

# 设置feign客户端超时时间(OpenFeign默认支持ribbon)
ribbon:
  # 建立连接后从服务器读取到可用资源所用的时间
  ReadTimeout: 3000
  # 建立连接所用的时间,适用于网络状况正常的情况下,两端连接所用的时间
  ConnectTimeout: 3000

feign:
  hystrix:
    enabled: true # 在feign中开启hystrix